version: 1.0
provider:
  name: openfaas
  # faasd's gateway. If you're running this faas-cli command directly on the
  # faasd host, 127.0.0.1:8080 is correct. If you're deploying remotely,
  # point this at that host's IP/domain (and put it behind TLS/auth in prod).
  gateway: http://127.0.0.1:8080

functions:
  planner:
    lang: python3-http
    handler: ./planner
    image: sankalps2003/planner:latest        # change to your own registry, e.g. docker.io/you/planner:latest
    environment:
      MOCK_LATENCY_S: "2.0"
      MOCK_LATENCY_JITTER_S: "0.0"
      MOCK_NUM_STEPS: "4"
      write_debug: "true"
      read_timeout: "90s"
      write_timeout: "90s"
      exec_timeout: "90s"
    secrets:
      - gemini-api-key

  actor:
    lang: python3-http
    handler: ./actor
    image: sankalps2003/actor:latest          # change to your own registry
    environment:
      MOCK_LATENCY_S: "2.0"
      MOCK_LATENCY_JITTER_S: "0.0"
      MOCK_ACTOR_TOOL_ROUNDS: "1"
      write_debug: "true"
      read_timeout: "180s"
      write_timeout: "180s"
      exec_timeout: "180s"
    secrets:
      - gemini-api-key
      - tavily-api-key
  evaluator:
    lang: python3-http
    handler: ./evaluator
    image: sankalps2003/evaluator:latest      # change to your own registry
    environment:
      MOCK_LATENCY_S: "1.0"
      MOCK_LATENCY_JITTER_S: "0.0"
      write_debug: "true"
      read_timeout: "90s"
      write_timeout: "90s"
      exec_timeout: "90s"
    secrets:
      - gemini-api-key
